[package]
name = "thecogumeta/specium"
description = "A simple and flexible testing framework for Roblox"
version = "1.2.2"
license = "MIT"
authors = ["Cogu (@thecogumeta)"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
exclude = ["**"]
include = ["lib", "lib/*", "lib/**/*", "default.project.json", "wally.toml"]

[dependencies]
